// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riohfaozsjeikczqjgzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpb2hmYW96c2plaWtjenFqZ3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjA0MDAsImV4cCI6MjA3NDM5NjQwMH0.qaVJGNKYkAHV4tm5kArBM5PQP8u8tmywn6GMwsBpg44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});