// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjblcpoakfuvwltoaoln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqYmxjcG9ha2Z1dndsdG9hb2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTUyMjMsImV4cCI6MjA3MTYzMTIyM30.800nsLwpyuD6zdh1p_5cP4aAyu1FZpjlyYdGA1OQmY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});